version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: ecommerce-mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} 
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ecommerce-cart-service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env 

volumes:
  db_data: