version: "3.9"
services:
  app:
    build: .
    container_name: ecommerce-cart-service
    networks:
      - ecommerce-network
    ports:
      - "${PORT_APP}:${PORT_APP}"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env

networks:
  ecommerce-network:
    external: true
